name: Docker and Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t random-quote-generator .

    - name: Run Docker container
      run: docker run -d --name random-quote-generator random-quote-generator

    - name: Run tests
      run: docker exec random-quote-generator npm test

    - name: Stop Docker container
      run: docker stop random-quote-generator